" ~/.config/nvim/init.vim

" == General configuration ==

set encoding=utf-8          " Set encoding
set nocompatible            " disable compatibility to old-time vi

set showmatch               " Highlight matching brace

set incsearch               " Incremental search
set hlsearch                " Highlight all search results
set ignorecase              " Ignore cases when searching
set smartcase               " With both ignorecase and smartcase turned on, a search is case-insensitive if you enter the search string in ALL lower case.

" command line completion
set wildmenu                   " Helpful completion menu
set wildmode=list:longest,full " First <tab> shows list of completions, second <tab> show wildmenu

"set mouse=v                 " middle-click paste with mouse

set tabstop=4               " One tab = 4 spaces
set softtabstop=4           " see multiple spaces as tabstops so <BS> does the right thing
set expandtab               " Use spaces instead of tabs
set shiftwidth=4            " Number of auto-indent spaces

set autoindent              " indent a new line the same amount as the line just typed
set smartindent             " Autoindent when starting a new line
set smarttab                " Tab insertion & deletion

set nowrap                  " Don't add an actual linebreak when wrapping
set linebreak               " Break lines at word (requires Wrap lines)
set textwidth=80            " Line wrap (number of cols)
set colorcolumn=80          " set colour columns for good coding style
set nolist                  " do not show carriage return marker ($)

set backspace=indent,eol,start

set number                  " add line numbers
set ruler                   " Show line & col number of cursor position

set visualbell              " Use visual bell (no beeping)

"filetype plugin indent on   " allow auto-indenting depending on file type
syntax on                   " syntax highlighting

""" Enable syntax
if has('syntax') && !exists('g:syntax_on')
    syntax enable
endif


""" Make , the leader key
let mapleader = ","


" == File Search (without plugins)

" Search down into subfolders
" Provides tab-completion for all file related tasks
set path+=**

" == Colors ==

" built-in schemes installed in `/usr/share/nvim/runtime/colors`; extra schemes in `~/.config/nvim/colors`
colorscheme default     " `default` picks up colors defined in `~/.Xresources`

set background=dark

set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" == Navigation ===

" move hjkl to jkl; (slide the block one key to the right)
"nnoremap ; l
"nnoremap l k
"nnoremap k j
"nnoremap j h

" move hjkl to j=Down/k=Up and l=Left/;=Right (i.e. jk is unchanged)
"nnoremap l h
"nnoremap ; l
"nnoremap h ;

" == Uncommented for future reference ==

" set complete-=i      " Set the matches for insert mode completion
" set formatoptions+=j " Delete comment character when joining commented lines
" set laststatus=1     " No status line


" Strings to use in 'list' mode and for the :list command
" set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+



" easy escape
imap jk <Esc>

" send to ix.io
" noremap <silent> <leader>i :w !ix<CR>

" Invoke tab-completion from a mapping
set wildcharm=<C-z>

" Mappings to access buffers (don't use "\p" because a
" delay before pressing "p" would accidentally paste).
" ,l       : list files/buffers
" ,n       : new file/buffer
" ,b       : switch file/buffer
" ,e       : edit/open file/buffer
" ,p       : find/open file/buffer (fuzzy find without any plugins)
" ,k       : kill/delete buffer (file is not deleted)
" ,[ ,] ,, : go back to prev / go forward to next / go to last-used
" ,1 ,2 ,3 : go to buffer 1/2/3 etc
nnoremap <leader>l :ls<CR>
nnoremap <leader>n :enew<CR>
nnoremap ;b        :ls<CR>:buffer<Space>
nnoremap <Leader>b :b <C-z>
" nnoremap ;b  :buffer <C-R>=expand("%:h") . "/" <CR>
nnoremap <leader>e :e <C-z>
nnoremap <Leader>p :e <C-z>
nnoremap <C-p>     :e <C-z>
" nnoremap ;e  :edit <C-R>=expand("%:h") . "/" <CR>
nnoremap <Leader>k :bd<CR>
nnoremap <Leader>[ :bp<CR>
nnoremap <Leader>] :bn<CR>
nnoremap <Leader>, :e#<CR>
nnoremap <Leader>1 :1b<CR>
nnoremap <Leader>2 :2b<CR>
nnoremap <Leader>3 :3b<CR>
nnoremap <Leader>4 :4b<CR>
nnoremap <Leader>5 :5b<CR>
nnoremap <Leader>6 :6b<CR>
nnoremap <Leader>7 :7b<CR>
nnoremap <Leader>8 :8b<CR>
nnoremap <Leader>9 :9b<CR>
nnoremap <Leader>0 :10b<CR>

" Open new split panes to right and bottom, which feels more natural
set splitbelow
set splitright

nnoremap <Leader>v :vs <C-z>
nnoremap <Leader>s :sp <C-z>

" Quicker window movement
nnoremap <C-j> <C-w>j " instead of ctrl-w then j, it’s just ctrl-j
nnoremap <C-k> <C-w>k " etc..
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Don't offer to open certain files/directories
set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png,*.ico
set wildignore+=*.pdf,*.psd
set wildignore+=node_modules/*,bower_components/*

" grep (ripgrep)
" nmap ,g  :Rg

" clear out trailing whitespace and lines ending in whitespace
nmap <silent> ,w   :%s/[\t ]\+$//e<cr>

" Use <C-L> to clear the highlighting of :set hlsearch.
if maparg('<C-L>', 'n') ==# ''
    nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
endif

" trailing spaces are always bad
syntax match Warning   display "\s\+$"
" mixed tabs and spaces
syntax match Warning   display " \+\t"
syntax match Warning   display "\t\+ "

" mark columns 80 and 81 in red for long lines...
"match ErrorMsg /\%80v.\%81v./

""" Easily find cursor with crosshair (,c)
" :hi CursorLine   cterm=NONE term=reverse ctermbg=7 guibg=Grey90
" :hi CursorColumn cterm=NONE term=reverse ctermbg=7 guibg=Grey90
" :nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>

""" File browser
" let g:netrw_banner=0       " Disable file browser banner
" let g:netrw_liststyle=3    " Tree view

""" CTAGS shortcuts
" open definition in a new tab:
"map <C-\> :tab split<CR>:exec("tag ".expand("<cword>"))<CR>
" open definition in a vertical split:
"map <A-]> :vsp <CR>:exec("tag ".expand("<cword>"))<CR>


""" Plugins with vim-plug
" 2019.06.11: disabling b/c I'd rather just use nix/home-manager for vim
" plugins, but this is nice code to have for reference too
"if empty(glob('~/.vim/autoload/plug.vim'))
"    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
"    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
"endif
"so ~/.vim/plugins.vim
