{ pkgs, ... }:

{
  # programs.vim = {
  #   enable = true;
  #   # plugins = [
  #   #   "ctrlp"
  #   #   "fugitive"
  #   #   "editorconfig-vim"
  #   #   "surround"
  #   #   "vim-colorschemes"
  #   # ];
  #   extraConfig = builtins.readFile ../dotfiles/vimrc;
  # };

  # TODO: XDG
  #home.file.".ideavimrc".source = ../dotfiles/ideavimrc;

  # Idea VIM plugin supports XDG_CONFIG_HOME
  xdg.configFile = {
    "ideavim/ideavimrc".text = ''
      ${builtins.readFile ../dotfiles/vimrc.base}
      ${builtins.readFile ../dotfiles/vimrc.idea}
    '';
  };

  # nvim is installed into the nix store in the following rather complex manner:
  #
  # $ which vim
  #   /home/maxfire/.nix-profile/bin/vim
  # $ readlink -f $(which vim)
  #   /nix/store/qk2jip85migg0msk5h1h9ffrsjn5h6yl-neovim-0.4.3/bin/nvim
  # $ cat $( readlink -f $(which vim) )
  #   #! /nix/store/kgp3vq8l9yb8mzghbw83kyr3f26yqvsz-bash-4.4-p23/bin/bash -e
  #   export NVIM_SYSTEM_RPLUGIN_MANIFEST='/nix/store/qk2jip85migg0msk5h1h9ffrsjn5h6yl-neovim-0.4.3/rplugin.vim'
  #   exec -a "$0" "/nix/store/qk2jip85migg0msk5h1h9ffrsjn5h6yl-neovim-0.4.3/bin/.nvim-wrapped"  -u /nix/store/5k975mynq33ag2arv58angs14nznjdnn-vimrc "$@"
  #
  # That is an .nvim-wrapped executable script is wrapped by a bash shell script, and the -u switch will pass the vimrc run script.
  # The .nvim-wrapped script is a bash shell script containing
  #
  #   #! /nix/store/kgp3vq8l9yb8mzghbw83kyr3f26yqvsz-bash-4.4-p23/bin/bash -e
  #   export PATH=$PATH${PATH:+':'}'/nix/store/3wql63ic2wxzk0vg23yx9ffbjh47zpnl-neovim-ruby-env/bin'
  #   export GEM_HOME='/nix/store/3wql63ic2wxzk0vg23yx9ffbjh47zpnl-neovim-ruby-env/lib/ruby/gems/2.6.0'
  #   exec "/nix/store/paik8rpjf0n0ai4p68831hvsmirhxqjw-neovim-unwrapped-0.4.3/bin/nvim" \
  #       --cmd "let g:loaded_node_provider=1" \
  #       --cmd "let g:python_host_prog='/nix/store/qk2jip85migg0msk5h1h9ffrsjn5h6yl-neovim-0.4.3/bin/nvim-python'" \
  #       --cmd "let g:python3_host_prog='/nix/store/qk2jip85migg0msk5h1h9ffrsjn5h6yl-neovim-0.4.3/bin/nvim-python3'" \
  #       --cmd "let g:ruby_host_prog='/nix/store/qk2jip85migg0msk5h1h9ffrsjn5h6yl-neovim-0.4.3/bin/nvim-ruby'" \
  #       "$@"
  #
  # The vimrc script is generated by the nix build and looks like
  #
  #   set nocompatible
  #
  #   set packpath^=/nix/store/6msjqf5xzqkw1gv313zzic01ii5p85vg-vim-pack-dir
  #   set runtimepath^=/nix/store/6msjqf5xzqkw1gv313zzic01ii5p85vg-vim-pack-dir
  #
  #   filetype indent plugin on | syn on
  #
  #   " Your vimrc config starts here (~/.config/nvim/init.vim)
  #   .
  #   .
  #
  # To list everything in the nix store related to Vim:
  # $ nix-store --query --requisites ~/.nix-profile/ | grep -P '^[^-]+-.*?\K\bvim'
  #   /nix/store/ynwh265h3sf0pjdic30bpicq54xgw9b6-vimplugin-editorconfig-vim-2020-04-07
  #   /nix/store/6msjqf5xzqkw1gv313zzic01ii5p85vg-vim-pack-dir
  #   /nix/store/5k975mynq33ag2arv58angs14nznjdnn-vimrc
  # $ nix-store --query --requisites ~/.nix-profile/ | grep -P 'vim'
  #   /nix/store/2h1cpk4bxycgb1n7xnyxkz7py37yp9ji-python3.7-pynvim-0.4.1
  #   /nix/store/9yiq86gmnibpb5x4m235wppzwr96w4lf-ruby2.6.6-neovim-0.8.0
  #   /nix/store/3wql63ic2wxzk0vg23yx9ffbjh47zpnl-neovim-ruby-env
  #   /nix/store/ynwh265h3sf0pjdic30bpicq54xgw9b6-vimplugin-editorconfig-vim-2020-04-07
  #   /nix/store/6msjqf5xzqkw1gv313zzic01ii5p85vg-vim-pack-dir
  #   /nix/store/5k975mynq33ag2arv58angs14nznjdnn-vimrc
  #   /nix/store/ykp21nmhlsy98ysh0kjl6fqdfsq6wxka-python2.7-pynvim-0.4.1
  #   /nix/store/xj1v8fxb15vs19llga269dxsp1ssjab7-libvterm-neovim-0.1.3
  #   /nix/store/paik8rpjf0n0ai4p68831hvsmirhxqjw-neovim-unwrapped-0.4.3
  #   /nix/store/qk2jip85migg0msk5h1h9ffrsjn5h6yl-neovim-0.4.
  #
  # See also http://ivanbrennan.nyc/2018-05-09/vim-on-nixos
  programs.neovim = {
    enable = true;
    viAlias = true;
    vimAlias = true;
    vimdiffAlias = true;
    plugins = with pkgs.vimPlugins; [
      #tagbar
      #gruvbox
      #nerdtree
      # fugitive
      # airline
      # multiple-cursors
      # surround
      # nerdcommenter
      # easymotion
      # vim-obsession
      #vim-prosession
      # syntastic
      # ultisnips
      # vim-snippets
      # deoplete-nvim
      # deoplete-rust
      # deoplete-clang
      # deoplete-jedi
      # rust-vim

      # fugitive
      # gitgutter
      # nerdcommenter
      # nerdtree
      # surround
      # syntastic
      # tmux-navigator
      # vim-airline
      # vim-indent-guides
      # vim-markdown
      # vim-multiple-cursors
      # vim-nix
      # vim-trailing-whitespace
      # vimproc
      # youcompleteme

      editorconfig-vim
      ctrlp
      fzf-vim
      fzfWrapper
      # LanguageClient-neovim
      # lightline-vim
      # nerdtree
      # supertab
      # tabular
      # vim-better-whitespace
      # vim-multiple-cursors
      vim-surround
      vim-commentary

      #vimproc
      #vimproc-vim

      # themes
      #wombat256

      # language packages
      # Haskell
      #vim-hoogle
      # neco-ghc
      # haskell-vim
      # hlint-refactor-vim
      # ghc-mod-vim

      # Nix
      vim-nix

      # Csharp
      #vim-csharp

      # Powershell
      #vim-ps1

      # Python
      #semshi
    ];

    extraConfig = ''
      ${builtins.readFile ../dotfiles/vimrc.base}
      ${builtins.readFile ../dotfiles/vimrc}
    '';

    # TODO: Move config to dotfiles
    # extraConfig = ''
    #   colorscheme wombat256mod

    #   set number
    #   set expandtab
    #   set foldmethod=indent
    #   set foldnestmax=5
    #   set foldlevelstart=99
    #   set foldcolumn=0

    #   set list
    #   set listchars=tab:>-

    #   let g:better_whitespace_enabled=1
    #   let g:strip_whitespace_on_save=1
    #   let mapleader=' '

    #   let g:SuperTabDefaultCompletionType = '<c-x><c-o>'

    #   if has("gui_running")
    #     imap <c-space> <c-r>=SuperTabAlternateCompletion("\<lt>c-x>\<lt>c-o>")<cr>
    #   else " no gui
    #     if has("unix")
    #       inoremap <Nul> <c-r>=SuperTabAlternateCompletion("\<lt>c-x>\<lt>c-o>")<cr>
    #     endif
    #   endif

    #   let g:haskellmode_completion_ghc = 0
    #   autocmd FileType haskell setlocal omnifunc=necoghc#omnifunc
    #   autocmd FileType markdown setlocal conceallevel=0

    #   " Tabular bindings
    #   let g:haskell_tabular = 1
    #   vmap <leader>a= :Tabularize /=<CR>
    #   vmap <leader>a; :Tabularize /::<CR>
    #   vmap <leader>a- :Tabularize /-><CR>
    #   vmap <leader>a# :Tabularize /#<CR>

    #   " fzf bindings
    #   nnoremap <leader>r :Rg<CR>
    #   nnoremap <leader>b :Buffers<CR>
    #   nnoremap <leader>e :Files<CR>
    #   nnoremap <leader>l :Lines<CR>
    #   nnoremap <leader>L :BLines<CR>
    #   nnoremap <leader>c :Commits<CR>
    #   nnoremap <leader>C :BCommits<CR>
    # '';
  };
}
